---
language: ruby
script:
- bundle exec rspec
rvm:
- rbx-18mode
- rbx-19mode
- 1.8.7
- 1.9.2
- 1.9.3
- 2.0.0
env:
  global:
  - secure: ! 'bq7hMboLVCQ+cNDME+P4dM5UdgQbxfPyg7RH/5lhlSXJN3wbKupX8hCVOPEI

      SDO/BKgVJSKlQLrFjamwhkjwlJOkdQOIJi3JNJPQY7+Jjn9SCgpfYxnm+g++

      gay4cl9kc6b7+NJla0c3SyCjIDQ+dtjgx9ODakPnnYVaby26+r4='
  - secure: ! 'Z3jkwv50DRsuGLCJuIhn7k5RRG+5AtR4E6T3PXrwkEEVtjspAxFVuswRH+CJ

      mp1SB0I3tXAandpsyAwk3VYixOBD+O+LAoyELYKhB/JF3W7SnU+zESJwY/GB

      ojvHwKBHsfS/EmZLUcMf1vlbNd3RVl7fYT/LBXM0c7QcD+cnZto='
  - secure: ! 'cLKKt6z2W+Zjms2dMR2Q21K5Ov6DNHkUvL2gv5N5N76hH34ua8h3wn80qk5l

      0u4ZTzbK7C0z8j8baCdbJDi9+8dn9ucpMXKuNfxDX+UL6EjM0tRkQA3B6tWk

      DEm54mi6Ij2GizXNVe8zmjlSIlfa2XP79jKLw1aQDOuyCgkovzA='
